### ISSUE TITLE
【bug】在服务器多世界情况下使用精英定位器无法显示矿脉类型

### ISSUE THREAD

**Issue by haha370104** [GWYOG/GTVeinLocator#1]
在服务器使用Multiverse-Core插件 用指令/mv create resworld normal
使用精英定位器在旅行地图上只会显示未知

**Comment by GWYOG** [comment]
多谢反馈，之后会开始调查。贴吧之前也收到了类似的反馈，不过这段时间我一直忙于毕业论文的答辩而无力抽身修复，实在万分抱歉。

**Comment by GWYOG** [comment]
原因已找到，现在在考虑解决方法。
造成这个问题的原因是GT默认只会在主世界、下届、末地和星系mod的月球和火星生成矿脉。由于各个世界能生成的矿脉类型和规模各不相同，GTVL为了更高效、更准确地判断矿脉类型，会在对应世界所能生成的矿脉类型中进行判断。
这样问题就出来了，Multiverse-Core这个多世界插件创建了除了这5个固定世界外新的、可以生成GT矿脉的世界，而GTVL并不清楚这个新id的世界所能生成的是和哪个世界生成矿脉类型对应的GT矿脉，所以只能显示未知。
目前我能想到的解决方案是在GTVL的配置文件中添加某个id的世界对应某种类型世界的地方，通过服主手动添加配置文件的方法让GTVL与Multiverse-Core兼容，不知你的意见如何？

**Comment by haha370104** [comment]
【其实都是我……mcbbs 贴吧和这里……
【解决方案我觉得不错
【我也要写毕业论文了……啊……

**Comment by GWYOG** [comment]
23333, 我明白了, 这几天我就着手修复, 毕设加油哦~

**Comment by GWYOG** [comment]
已在配置文件中添加对多世界插件的支持，下个发布的版本将加入此特性~
