### ISSUE TITLE
兼容gt6嘛……

### ISSUE THREAD

**Issue by indoorsNB** [GWYOG/GTVeinLocator#2]
如题

**Comment by GWYOG** [comment]
抱歉这么晚才回复，这段时间一直忙于毕业论文的答辩而没上GitHub.
之后应该是会兼容gt6的，不过之前(大概有1个半月了...)看了下gt6的源代码，它关于矿脉坐标的公式似乎比起gt5发生了些变化，不再像之前一样那么工整地生成了，所以对gt6的兼容可能还需要一段时间。

**Comment by indoorsNB** [comment]
奥，感谢大佬 XD

**Comment by GWYOG** [comment]
刚才又去看了下GT6的代码...最后才发现GT6矿脉生成机制和GT5基本上是一模一样(除了GT5坐标公式负坐标的部分被"修复"外)，只是作者将代码换成了另一种比较难看懂的写法.....
总之这样就好办多了，下周有空的时候我应该会做好对GT6的兼容然后发布一个新版本.

**Comment by indoorsNB** [comment]
赞
顺便问一下一个问题
GT6矿物生成也是原来那种3x3区块那种还是变了，我在单机测试的时候好像不长这样了

**Comment by GWYOG** [comment]
已加入对GT6的支持，新版本大概明天或后天发吧

**Comment by indoorsNB** [comment]
铪铪，老哥稳
汉化在我的组织里有，我觉得空集应该给了。。那个没汉化的真有点蒙b。。。
Dolamide是一种药物

**Comment by GWYOG** [comment]
据空集说那个矿脉里面的另一种物质来自《星际迷航》，不过译名有多种，等gt6的汉化完工后我再补全这儿的汉化吧

**Comment by GWYOG** [comment]
已发布新版本1.0.6~

**Comment by indoorsNB** [comment]
哦，点赞👍
